package gateway

import (
	"sync"

	"github.com/jaevor/go-nanoid"

	"darvin-cowork/backend/internal/agent/session"
)

// sessionIDLen is the length of session / message ids generated by the
// gateway. 21 chars from a 62-symbol alphabet gives ~125 bits of entropy,
// matching go-nanoid's canonical length.
const sessionIDLen = 21

// sessionAlphabet is the pure-ASCII [A-Za-z0-9] table — nanoid's fast
// path. We avoid the Unicode / unsafe variants because session ids appear
// in URLs and JSON where the [A-Za-z0-9_-] canon would still need escaping.
const sessionAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// SessionManager is the in-memory index from session id to *session.Session.
// S3 keeps it process-local; EventLedger persistence to sessions.db is
// deferred to S4 when the handler actually runs Agent.Run.
type SessionManager struct {
	mu       sync.Mutex
	sessions map[string]*session.Session
	idGen    func() string // 21-char nanoid
}

// NewSessionManager builds a manager with the default 21-char nanoid
// generator seeded from go-nanoid's CSPRNG.
func NewSessionManager() *SessionManager {
	return &SessionManager{
		sessions: make(map[string]*session.Session),
		idGen:    nanoid.MustCustomASCII(sessionAlphabet, sessionIDLen),
	}
}

// CreateOrGet returns the session identified by id. If id is empty a new
// session is created with a fresh nanoid. A fresh message id is always
// generated and returned alongside the session — message ids are *not*
// tied to the session lifecycle, they're just a handle the caller can use
// to correlate emitted events.
func (m *SessionManager) CreateOrGet(id string) (*session.Session, string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	msgID := m.idGen()
	if id != "" {
		if s, ok := m.sessions[id]; ok {
			return s, msgID, nil
		}
	}
	sess := session.NewSession(m.idGen()) // NewSession already stamps CreatedAt + Status.
	m.sessions[sess.ID] = sess
	return sess, msgID, nil
}

// Has reports whether id is a known session. Subscribe handlers use this
// to fail fast on unknown session ids before touching the ledger.
func (m *SessionManager) Has(id string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()
	_, ok := m.sessions[id]
	return ok
}

// Get returns the session and a fresh message id. If id is unknown it
// behaves like CreateOrGet: a new session is created and returned.
func (m *SessionManager) Get(id string) (*session.Session, string) {
	sess, msgID, _ := m.CreateOrGet(id)
	return sess, msgID
}
